<?php
namespace Appress\Controllers\Login;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * QR-Code Login — device-linked sign-in flow.
 *
 *   1. Web (logged-out) calls `qr_login.start` → server mints a session
 *      token (TTL 60s), returns it + a QR payload.
 *   2. Web shows the QR + polls `qr_login.poll(session)` every ~1.5s.
 *   3. User opens the Appress mobile app (already signed in), scans the
 *      QR via the in-app native scanner, taps Confirm in the app.
 *   4. App calls `qr_login.approve(session)` with its WP cookie auth →
 *      server records the user_id on the session row.
 *   5. Web's next poll sees `approved`, server sets the auth cookie for
 *      that user, response signals the front-end to reload.
 *
 * Sessions live in transients (auto-expire in 60s) so we don't need a
 * dedicated DB table; the volume of in-flight QR sessions on a typical
 * site is low (one per browser tab attempting the flow).
 *
 * Security model — see the user-chosen pared-down threat model: a single
 * user-tap confirmation in the mobile app + 60s TTL + single-use token
 * is enough. No IP/UA disclosure to the user; no session binding to the
 * web initiator's IP (would break legitimate cellular hand-offs).
 */
class Qr_Login_Controller extends \Appress\Controllers\Base_Controller {

	const TRANSIENT_PREFIX = 'appress_qr_login_';
	const TTL_SECONDS      = 60;
	const TOKEN_BYTES      = 24;

	protected function hooks() {
		// `start` + `poll` are called by the WEB initiator (browser modal),
		// not the mobile app — stay on the `appress_ajax_*` prefix the
		// existing web JS uses. `nopriv` because the browser is by definition
		// not yet logged in (login is the whole point).
		$this->on( 'appress_ajax_qr_login.start',          '@handle_start' );
		$this->on( 'appress_ajax_nopriv_qr_login.start',   '@handle_start' );
		$this->on( 'appress_ajax_qr_login.poll',           '@handle_poll' );
		$this->on( 'appress_ajax_nopriv_qr_login.poll',    '@handle_poll' );

		// `approve` + `deny` are called by the MOBILE APP after the in-app
		// scanner reads the QR — register on each app's `<class_id>_ajax_*`
		// prefix + legacy `appress_ajax_*` for backward compat.
		$this->on_mobile( 'qr_login.approve', '@handle_approve' );
		$this->on_mobile( 'qr_login.deny',    '@handle_deny' );
	}

	/**
	 * Mint a fresh QR session. Returns a token + the encoded QR payload
	 * the web modal renders. Payload format (`applogin:<v>:<host>:<token>`)
	 * is what the in-app scanner parses — `host` lets the app refuse a
	 * QR generated by a different site if the same app shell is used
	 * across multiple Appress installations.
	 */
	protected function handle_start() {
		try {
			$token = bin2hex( random_bytes( self::TOKEN_BYTES ) );
			$session = [
				'token'       => $token,
				'status'      => 'pending',
				'user_id'     => 0,
				'created_at'  => time(),
			];
			set_transient( self::TRANSIENT_PREFIX . $token, $session, self::TTL_SECONDS );

			$host    = wp_parse_url( home_url(), PHP_URL_HOST ) ?: '';
			$payload = 'applogin:1:' . $host . ':' . $token;

			return wp_send_json([
				'success' => true,
				'data'    => [
					'token'       => $token,
					'qr_payload'  => $payload,
					'expires_in'  => self::TTL_SECONDS,
				],
			]);
		} catch ( \Exception $e ) {
			return wp_send_json([ 'success' => false, 'message' => $e->getMessage() ]);
		}
	}

	/**
	 * Web polls this. While `pending`, just echoes status. When the app
	 * has called `approve`, this handler logs the web user in via
	 * `wp_set_auth_cookie` (the cookie ships in this very response, so
	 * the next request the browser makes is authenticated) and marks the
	 * session consumed so a second poll can't re-use the same token.
	 */
	protected function handle_poll() {
		try {
			// Nonce verification is intentionally skipped on the QR-login
			// AJAX surface. The 24-byte (192-bit) cryptographically random
			// token issued by handle_start() IS the request authenticator —
			// it lives in a single-use 60-second transient and rotates per
			// session, so it serves the same role a nonce would. Adding a
			// WP nonce on top would either tie the request to the
			// originator's logged-out session (where nonces are weak) or
			// prevent the cross-device hand-off that the flow requires (the
			// approve call comes from a different device than the poll).
			// phpcs:ignore WordPress.Security.NonceVerification.Missing
			$token = isset( $_POST['token'] ) ? sanitize_text_field( wp_unslash( $_POST['token'] ) ) : '';
			if ( $token === '' ) {
				throw new \Exception( esc_html__( 'Missing token.', 'appress' ) );
			}

			$session = get_transient( self::TRANSIENT_PREFIX . $token );
			if ( ! is_array( $session ) ) {
				return wp_send_json([ 'success' => true, 'data' => [ 'status' => 'expired' ] ]);
			}

			if ( $session['status'] === 'approved' ) {
				$user_id = (int) $session['user_id'];
				if ( $user_id > 0 && get_user_by( 'id', $user_id ) ) {
					wp_set_auth_cookie( $user_id, true );
					// `wp_login` is a WordPress core action, not a custom
					// plugin hook — we fire it so security plugins, login
					// analytics, and session managers see the QR sign-in as
					// a normal login event. Prefixing it would defeat that.
					// phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound
					do_action( 'wp_login', get_userdata( $user_id )->user_login, get_userdata( $user_id ) );
				}
				delete_transient( self::TRANSIENT_PREFIX . $token );
				return wp_send_json([
					'success' => true,
					'data'    => [
						'status'   => 'approved',
						'redirect' => apply_filters( 'appress/qr_login/redirect_url', home_url( '/' ), $user_id ),
					],
				]);
			}

			if ( $session['status'] === 'denied' ) {
				delete_transient( self::TRANSIENT_PREFIX . $token );
				return wp_send_json([ 'success' => true, 'data' => [ 'status' => 'denied' ] ]);
			}

			return wp_send_json([ 'success' => true, 'data' => [ 'status' => 'pending' ] ]);
		} catch ( \Exception $e ) {
			return wp_send_json([ 'success' => false, 'message' => $e->getMessage() ]);
		}
	}

	/**
	 * App calls this after the user taps Confirm in the native scanner.
	 * Auth comes from the app's WebView WP cookie — already-logged-in
	 * user; we do not need a separate token. We DO require the QR token
	 * so the app proves it scanned a real-shown QR (not a guessed string).
	 */
	protected function handle_approve() {
		try {
			if ( ! is_user_logged_in() ) {
				throw new \Exception( esc_html__( 'You must be signed in to approve.', 'appress' ) );
			}
			// See handle_poll() — the 24-byte random token is the request
			// authenticator; nonce check is omitted on purpose.
			// phpcs:ignore WordPress.Security.NonceVerification.Missing
			$token = isset( $_POST['token'] ) ? sanitize_text_field( wp_unslash( $_POST['token'] ) ) : '';
			if ( $token === '' ) {
				throw new \Exception( esc_html__( 'Missing token.', 'appress' ) );
			}

			$session = get_transient( self::TRANSIENT_PREFIX . $token );
			if ( ! is_array( $session ) ) {
				throw new \Exception( esc_html__( 'QR code expired. Try again.', 'appress' ) );
			}
			if ( $session['status'] !== 'pending' ) {
				throw new \Exception( esc_html__( 'QR code already used.', 'appress' ) );
			}

			$session['status']  = 'approved';
			$session['user_id'] = get_current_user_id();
			// Fresh TTL so the polling web side has a window to pick up
			// the approved state even if approve happened near the original
			// 60s edge.
			set_transient( self::TRANSIENT_PREFIX . $token, $session, self::TTL_SECONDS );

			return wp_send_json([
				'success' => true,
				'message' => __( 'Sign-in approved.', 'appress' ),
			]);
		} catch ( \Exception $e ) {
			return wp_send_json([ 'success' => false, 'message' => $e->getMessage() ]);
		}
	}

	/**
	 * User taps Cancel in the native confirm dialog. Marks the session
	 * denied so the web side breaks out of its poll loop with a clear
	 * "request rejected" state instead of timing out silently.
	 */
	protected function handle_deny() {
		try {
			if ( ! is_user_logged_in() ) {
				throw new \Exception( esc_html__( 'You must be signed in.', 'appress' ) );
			}
			// See handle_poll() — the 24-byte random token is the request
			// authenticator; nonce check is omitted on purpose.
			// phpcs:ignore WordPress.Security.NonceVerification.Missing
			$token = isset( $_POST['token'] ) ? sanitize_text_field( wp_unslash( $_POST['token'] ) ) : '';
			if ( $token === '' ) {
				throw new \Exception( esc_html__( 'Missing token.', 'appress' ) );
			}
			$session = get_transient( self::TRANSIENT_PREFIX . $token );
			if ( is_array( $session ) ) {
				$session['status'] = 'denied';
				set_transient( self::TRANSIENT_PREFIX . $token, $session, self::TTL_SECONDS );
			}
			return wp_send_json([ 'success' => true ]);
		} catch ( \Exception $e ) {
			return wp_send_json([ 'success' => false, 'message' => $e->getMessage() ]);
		}
	}
}
