<?php

namespace Appress\Integration\Translatepress\Controllers;

use Appress\Controllers\Base_Controller;
use Appress\Integration\Translatepress\Services\Url_Translator;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Per-app TranslatePress settings: enable/disable flag + bottom nav label
 * translations keyed by stable tab `_id`. The integration detail page
 * (`?page=appress-integrations&integration=translatepress`) reads/writes
 * through this controller's AJAX surface.
 *
 * Storage: one option per app, autoload=false (boot endpoint reads
 * explicitly, no admin-bar / front-end need for the data).
 *
 *   appress_app_translatepress_settings_{app_id} = [
 *     'enabled' => bool,
 *     'strings' => [
 *       '<tab_id>' => [ '<lang_code>' => '<translated text>' ],
 *       ...
 *     ],
 *   ]
 *
 * Tab `_id` is generated by the Vue admin when the admin adds a bottom-nav
 * item (see `BottomNavigationSettings.vue::genId`) and persists across
 * rename/reorder, so translations don't orphan when admins iterate.
 */
class Settings_Controller extends Base_Controller {

	const OPTION_PREFIX = 'appress_app_translatepress_settings_';

	protected function hooks() {
		$this->on( 'appress_ajax_integrations.translatepress.save_settings', '@handle_save_settings' );
		$this->on( 'appress_ajax_integrations.translatepress.clear_cache',   '@handle_clear_cache' );

		if ( is_admin() ) {
			$this->on( 'admin_enqueue_scripts', '@enqueue_assets' );
		}
	}

	// ── Storage helpers (used by Boot_Config_Controller + AJAX handlers) ──

	public static function get_settings( int $app_id ): array {
		$opt = get_option( self::OPTION_PREFIX . $app_id );
		if ( ! is_array( $opt ) ) {
			return [ 'enabled' => false, 'strings' => [] ];
		}
		return [
			'enabled' => ! empty( $opt['enabled'] ),
			'strings' => is_array( $opt['strings'] ?? null ) ? $opt['strings'] : [],
		];
	}

	public static function set_settings( int $app_id, array $settings ): void {
		$clean = [
			'enabled' => ! empty( $settings['enabled'] ),
			'strings' => is_array( $settings['strings'] ?? null ) ? $settings['strings'] : [],
		];
		update_option( self::OPTION_PREFIX . $app_id, $clean, false );

		// Single cache-invalidation signal: bump the app's `update_time_hash`.
		// This rotates the Boot_Config_Controller signature (which folds
		// update_time_hash + admin_settings into its hash), so the next
		// boot misses the per-(app, lang) cache option and rebuilds in
		// place. Same versioning mechanism as Apps_Controller's `app.save`
		// — keeps the cache-busting model uniform across the plugin and
		// avoids manually deleting cache entries on every settings change.
		self::bump_app_version_hash( $app_id );
	}

	/**
	 * Rotate the app row's `live_config.update_time_hash`. Matches the
	 * pattern in Apps_Controller::handle_save_config (line 482) — single
	 * source of truth for the "config has changed" signal that the
	 * Frontend_Controller boot endpoint reads.
	 */
	private static function bump_app_version_hash( int $app_id ): void {
		global $wpdb;
		$table = $wpdb->prefix . 'appress_apps';
		$row   = $wpdb->get_row(
			$wpdb->prepare( "SELECT build_config FROM {$table} WHERE id = %d", $app_id ),
			ARRAY_A
		);
		if ( empty( $row ) ) {
			return;
		}
		$live_config = ! empty( $row['build_config'] ) ? json_decode( $row['build_config'], true ) : [];
		if ( ! is_array( $live_config ) ) {
			$live_config = [];
		}
		$live_config['update_time_hash'] = (string) time();
		$wpdb->update(
			$table,
			[ 'build_config' => wp_json_encode( $live_config ) ],
			[ 'id' => $app_id ]
		);
	}

	public static function is_enabled_for_app( int $app_id ): bool {
		return ! empty( self::get_settings( $app_id )['enabled'] );
	}

	// ── Asset enqueue on the integration detail page ──

	protected function enqueue_assets() {
		$page        = isset( $_GET['page'] ) ? sanitize_text_field( wp_unslash( $_GET['page'] ) ) : '';
		$integration = isset( $_GET['integration'] ) ? sanitize_text_field( wp_unslash( $_GET['integration'] ) ) : '';
		if ( $page !== 'appress-integrations' || $integration !== 'translatepress' ) {
			return;
		}

		wp_enqueue_style( 'appress:admin.css' );
		wp_enqueue_script( 'appress:integration-translatepress.js' );

		$payload = wp_json_encode( $this->build_localize() );
		wp_add_inline_script(
			'appress:integration-translatepress.js',
			'window.appressTrpConfig=' . $payload . ';',
			'before'
		);
	}

	private function build_localize(): array {
		global $wpdb;
		$rows = $wpdb->get_results(
			"SELECT id, app_name, build_config FROM {$wpdb->prefix}appress_apps ORDER BY id ASC",
			ARRAY_A
		);

		$translator   = new Url_Translator();
		$trp_settings = $translator->get_settings();

		$apps = [];
		foreach ( (array) $rows as $row ) {
			$app_id      = (int) $row['id'];
			$live_config = ! empty( $row['build_config'] ) ? json_decode( $row['build_config'], true ) : [];
			if ( ! is_array( $live_config ) ) {
				$live_config = [];
			}

			$tabs = [];
			foreach ( (array) ( $live_config['bottom_navigation']['items'] ?? [] ) as $item ) {
				if ( empty( $item['_id'] ) ) {
					continue; // Skip legacy rows without a stable id — admin needs to re-save once.
				}
				$tabs[] = [
					'_id'   => (string) $item['_id'],
					'title' => (string) ( $item['title'] ?? '' ),
					'icon'  => (string) ( $item['icon'] ?? '' ),
				];
			}

			$settings = self::get_settings( $app_id );

			$apps[] = [
				'id'           => $app_id,
				'name'         => (string) $row['app_name'],
				'enabled'      => $settings['enabled'],
				'tabs'         => $tabs,
				// Cast to object so wp_json_encode emits `{}` for empty
				// instead of `[]`. Vue treats the value as a dictionary
				// (set keys by tab _id); a JS array with string-named
				// properties stringifies back to `[]`, losing the user's
				// input on save.
				'translations' => (object) ( is_array( $settings['strings'] ) ? $settings['strings'] : [] ),
			];
		}

		$language_codes = array_unique( array_filter( array_merge(
			[ $trp_settings['default_language'] ?? '' ],
			(array) ( $trp_settings['languages'] ?? [] )
		) ) );
		$language_names = $translator->get_language_names( $language_codes );

		return [
			'nonce'   => wp_create_nonce( 'appress_admin_action' ),
			'ajaxUrl' => home_url( '/?appress=1' ),
			'trp'     => [
				'active'           => $translator->is_active(),
				'default_language' => $trp_settings['default_language'] ?? '',
				'languages'        => $trp_settings['languages'] ?? [],
				'language_names'   => (object) $language_names,
			],
			'apps'    => $apps,
			'i18n'    => $this->vue_strings(),
		];
	}

	private function vue_strings(): array {
		// Page-specific strings only; shared admin dict is loaded by other
		// admin entries that need it.
		return [
			'TranslatePress'                      => __( 'TranslatePress', 'appress' ),
			'Enable for this app'                 => __( 'Enable for this app', 'appress' ),
			'Bottom Navigation'                   => __( 'Bottom Navigation', 'appress' ),
			'Clear cache'                         => __( 'Clear cache', 'appress' ),
			'Clearing…'                           => __( 'Clearing…', 'appress' ),
			'Save'                                => __( 'Save', 'appress' ),
			'Saving…'                             => __( 'Saving…', 'appress' ),
			'Saved'                               => __( 'Saved', 'appress' ),
			'Cache cleared'                       => __( 'Cache cleared', 'appress' ),
			'No bottom navigation tabs yet'       => __( 'No bottom navigation tabs configured for this app yet.', 'appress' ),
			'No apps yet'                         => __( 'Create an app first to configure translations.', 'appress' ),
			'TranslatePress plugin not detected'  => __( 'TranslatePress plugin is not active. Activate it to use this integration.', 'appress' ),
			'No published languages'              => __( 'TranslatePress has no published languages besides the default. Add languages in the TranslatePress settings.', 'appress' ),
		];
	}

	// ── AJAX handlers ──

	protected function handle_save_settings() {
		try {
			$this->require_admin();

			$app_id = isset( $_POST['app_id'] ) ? (int) $_POST['app_id'] : 0;
			if ( $app_id <= 0 ) {
				throw new \Exception( esc_html__( 'Invalid app id.', 'appress' ) );
			}

			$enabled     = ! empty( $_POST['enabled'] );
			$strings_raw = isset( $_POST['strings'] ) ? wp_unslash( $_POST['strings'] ) : '';
			$strings     = is_string( $strings_raw ) ? json_decode( $strings_raw, true ) : null;
			if ( ! is_array( $strings ) ) {
				$strings = [];
			}

			// Whitelist tab ids against the app's current schema so admins
			// can't write arbitrary keys (defense-in-depth — UI won't, but
			// the endpoint is the security boundary).
			$valid_ids = $this->valid_tab_ids_for_app( $app_id );

			$clean = [];
			foreach ( $strings as $tab_id => $by_lang ) {
				$tab_id = (string) $tab_id;
				if ( ! in_array( $tab_id, $valid_ids, true ) ) {
					continue;
				}
				if ( ! is_array( $by_lang ) ) {
					continue;
				}
				$entry = [];
				foreach ( $by_lang as $lang => $value ) {
					$lang  = sanitize_text_field( (string) $lang );
					$value = sanitize_text_field( (string) $value );
					if ( $lang === '' || $value === '' ) {
						continue;
					}
					$entry[ $lang ] = $value;
				}
				if ( ! empty( $entry ) ) {
					$clean[ $tab_id ] = $entry;
				}
			}

			self::set_settings( $app_id, [
				'enabled' => $enabled,
				'strings' => $clean,
			] );

			// set_settings() above bumped update_time_hash → next boot
			// fetch hits a signature mismatch in Boot_Config_Controller
			// and rebuilds the per-(app, lang) compiled mutations. No
			// extra cache-flush call needed.
			return wp_send_json([
				'success' => true,
				'message' => esc_html__( 'Settings saved.', 'appress' ),
			]);
		} catch ( \Exception $e ) {
			return wp_send_json([ 'success' => false, 'message' => $e->getMessage() ]);
		}
	}

	protected function handle_clear_cache() {
		try {
			$this->require_admin();
			$app_id = isset( $_POST['app_id'] ) ? (int) $_POST['app_id'] : 0;
			if ( $app_id <= 0 ) {
				throw new \Exception( esc_html__( 'Invalid app id.', 'appress' ) );
			}
			// "Clear cache" = bump version hash. Next boot fetch from any
			// client sees the mismatch, Boot_Config_Controller rebuilds
			// its per-(app, lang) compiled mutation set inline, and the
			// stale data is overwritten in place. No need to manually
			// delete option rows.
			self::bump_app_version_hash( $app_id );
			return wp_send_json([
				'success' => true,
				'message' => esc_html__( 'Cache cleared.', 'appress' ),
			]);
		} catch ( \Exception $e ) {
			return wp_send_json([ 'success' => false, 'message' => $e->getMessage() ]);
		}
	}

	private function require_admin(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			throw new \Exception( esc_html__( 'Permission denied.', 'appress' ) );
		}
		$nonce = isset( $_SERVER['HTTP_X_WP_NONCE'] ) ? sanitize_text_field( wp_unslash( $_SERVER['HTTP_X_WP_NONCE'] ) ) : '';
		if ( ! wp_verify_nonce( $nonce, 'appress_admin_action' ) ) {
			throw new \Exception( esc_html__( 'Security verification failed.', 'appress' ) );
		}
	}

	private function valid_tab_ids_for_app( int $app_id ): array {
		global $wpdb;
		$row = $wpdb->get_row(
			$wpdb->prepare( "SELECT build_config FROM {$wpdb->prefix}appress_apps WHERE id = %d", $app_id ),
			ARRAY_A
		);
		if ( ! $row ) {
			return [];
		}
		$live_config = ! empty( $row['build_config'] ) ? json_decode( $row['build_config'], true ) : [];
		$ids         = [];
		foreach ( (array) ( $live_config['bottom_navigation']['items'] ?? [] ) as $item ) {
			if ( ! empty( $item['_id'] ) ) {
				$ids[] = (string) $item['_id'];
			}
		}
		return $ids;
	}

	// ── Detail page render entry ──

	public static function render() {
		// Mount target for the Vue panel. The wrapping `#appress-integrations-app`
		// (provided by Integrations\Admin_Controller::render_integration_detail)
		// already carries the Tailwind scope, so this just needs a child div.
		echo '<div class="appress-trp-settings-mount"></div>';
	}
}
